name: Run Postman Collection Tests

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'  # This ensures you use the latest LTS version of Node.js

    - name: Install Newman
      run: npm install -g newman

    - name: Create Results Directory
      run: mkdir -p results

    - name: Run Postman Collection
      run: |
        newman run Reqres_REST_API_Test.postman_collection.json \
            --reporters cli,json \
            --reporter-json-export results/TESTS-results.json

    - name: List results directory
      run: ls -la results/

    - name: Upload Test Results
      if: always() # Ensures this step runs even if previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: results/TESTS-results.json
